name = "output-load-balancer"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "KV_API_REQUESTS_COUNTER"
id = "1d69b5918c8744709c39c667c9be1546"

[[kv_namespaces]]
binding = "KV_API_HEALTH"
id = "9ca4e55d63b84014bac0f1bc6c499341"